//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace {0}
{{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]{4}
    public interface I{1} : RomanticWeb.Entities.IEntity
    {{{3}
    }}

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class {1} : I{1}
    {{
        private RomanticWeb.Entities.EntityId _id = new RomanticWeb.Entities.EntityId(new System.Uri("urn:guid:" + System.Guid.NewGuid()));

        RomanticWeb.IEntityContext RomanticWeb.Entities.IEntity.Context {{ get {{ return null; }} }}

        RomanticWeb.Entities.EntityId RomanticWeb.Entities.IEntity.Id {{ get {{ return _id; }} }}{2}
    }}
}}