md "%CD%\..\NugetBuild\URSA.Tools\lib"
md "%CD%\..\NugetBuild\URSA.Tools\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Tools\lib\net45"
copy "%CD%\..\RSA.Tools\bin\Debug\netstandard1.6\URSA.Tools.dll" "%CD%\..\NugetBuild\URSA.Tools\lib\netstandard1.6"
copy "%CD%\..\URSA.Tools\bin\Debug\netstandard1.6\URSA.Tools.pdb" "%CD%\..\NugetBuild\URSA.Tools\lib\netstandard1.6"
copy "%CD%\..\URSA.Tools\bin\Debug\URSA.Tools.dll" "%CD%\..\NugetBuild\URSA.Tools\lib\net45"
copy "%CD%\..\URSA.Tools\bin\Debug\URSA.Tools.pdb" "%CD%\..\NugetBuild\URSA.Tools\lib\net45"
copy "%CD%\..\URSA.Tools\bin\Debug\URSA.Tools.xml" "%CD%\..\NugetBuild\URSA.Tools\lib\net45"
md "%CD%\..\NugetBuild\URSA.Core\lib"
md "%CD%\..\NugetBuild\URSA.Core\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Core\lib\net45"
copy "%CD%\..\URSA.Core\bin\Debug\netstandard1.6\URSA.Core.dll" "%CD%\..\NugetBuild\URSA.Core\lib\netstandard1.6"
copy "%CD%\..\URSA.Core\bin\Debug\netstandard1.6\URSA.Core.pdb" "%CD%\..\NugetBuild\URSA.Core\lib\netstandard1.6"
copy "%CD%\..\URSA.Core\bin\Debug\URSA.Core.dll" "%CD%\..\NugetBuild\URSA.Core\lib\net45"
copy "%CD%\..\URSA.Core\bin\Debug\URSA.Core.pdb" "%CD%\..\NugetBuild\URSA.Core\lib\net45"
copy "%CD%\..\URSA.Core\bin\Debug\URSA.Core.xml" "%CD%\..\NugetBuild\URSA.Core\lib\net45"
md "%CD%\..\NugetBuild\URSA.Http\lib"
md "%CD%\..\NugetBuild\URSA.Http\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Http\lib\net45"
copy "%CD%\..\URSA.Http\bin\Debug\netstandard1.6\URSA.Http.dll" "%CD%\..\NugetBuild\URSA.Http\lib\netstandard1.6"
copy "%CD%\..\URSA.Http\bin\Debug\netstandard1.6\URSA.Http.pdb" "%CD%\..\NugetBuild\URSA.Http\lib\netstandard1.6"
copy "%CD%\..\URSA.Http\bin\Debug\URSA.Http.dll" "%CD%\..\NugetBuild\URSA.Http\lib\net45"
copy "%CD%\..\URSA.Http\bin\Debug\URSA.Http.pdb" "%CD%\..\NugetBuild\URSA.Http\lib\net45"
copy "%CD%\..\URSA.Http\bin\Debug\URSA.Http.xml" "%CD%\..\NugetBuild\URSA.Http\lib\net45"
md "%CD%\..\NugetBuild\URSA.Http.Description\lib"
md "%CD%\..\NugetBuild\URSA.Http.Description\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Http.Description\lib\net45"
copy "%CD%\..\URSA.Http.Description\bin\Debug\netstandard1.6\URSA.Http.Description.dll" "%CD%\..\NugetBuild\URSA.Http.Description\lib\netstandard1.6"
copy "%CD%\..\URSA.Http.Description\bin\Debug\netstandard1.6\URSA.Http.Description.pdb" "%CD%\..\NugetBuild\URSA.Http.Description\lib\netstandard1.6"
copy "%CD%\..\URSA.Http.Description\bin\Debug\URSA.Http.Description.dll" "%CD%\..\NugetBuild\URSA.Http.Description\lib\net45"
copy "%CD%\..\URSA.Http.Description\bin\Debug\URSA.Http.Description.pdb" "%CD%\..\NugetBuild\URSA.Http.Description\lib\net45"
copy "%CD%\..\URSA.Http.Description\bin\Debug\URSA.Http.Description.xml" "%CD%\..\NugetBuild\URSA.Http.Description\lib\net45"
md "%CD%\..\NugetBuild\URSA.AutoFac\lib"
md "%CD%\..\NugetBuild\URSA.AutoFac\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.AutoFac\lib\net45"
copy "%CD%\..\URSA.AutoFac\bin\Debug\netstandard1.6\URSA.AutoFac.dll" "%CD%\..\NugetBuild\URSA.AutoFac\lib\netstandard1.6"
copy "%CD%\..\URSA.AutoFac\bin\Debug\netstandard1.6\URSA.AutoFac.pdb" "%CD%\..\NugetBuild\URSA.AutoFac\lib\netstandard1.6"
copy "%CD%\..\URSA.AutoFac\bin\Debug\URSA.AutoFac.dll" "%CD%\..\NugetBuild\URSA.AutoFac\lib\net45"
copy "%CD%\..\URSA.AutoFac\bin\Debug\URSA.AutoFac.pdb" "%CD%\..\NugetBuild\URSA.AutoFac\lib\net45"
copy "%CD%\..\URSA.AutoFac\bin\Debug\URSA.AutoFac.xml" "%CD%\..\NugetBuild\URSA.AutoFac\lib\net45"
md "%CD%\..\NugetBuild\URSA.CastleWindsor\lib"
md "%CD%\..\NugetBuild\URSA.CastleWindsor\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.CastleWindsor\bin\Debug\URSA.CastleWindsor.dll" "%CD%\..\NugetBuild\URSA.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.CastleWindsor\bin\Debug\URSA.CastleWindsor.pdb" "%CD%\..\NugetBuild\URSA.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.CastleWindsor\bin\Debug\URSA.CastleWindsor.xml" "%CD%\..\NugetBuild\URSA.CastleWindsor\lib\net45"
md "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib"
md "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\net45"
copy "%CD%\..\URSA.Http.AutoFac\bin\Debug\netstandard1.6\URSA.AutoFac.dll" "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\netstandard1.6"
copy "%CD%\..\URSA.Http.AutoFac\bin\Debug\netstandard1.6\URSA.AutoFac.pdb" "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\netstandard1.6"
copy "%CD%\..\URSA.Http.AutoFac\bin\Debug\URSA.AutoFac.dll" "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\net45"
copy "%CD%\..\URSA.Http.AutoFac\bin\Debug\URSA.AutoFac.pdb" "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\net45"
copy "%CD%\..\URSA.Http.AutoFac\bin\Debug\URSA.AutoFac.xml" "%CD%\..\NugetBuild\URSA.Http.AutoFac\lib\net45"
md "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib"
md "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.Http.CastleWindsor\bin\Debug\URSA.CastleWindsor.dll" "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.Http.CastleWindsor\bin\Debug\URSA.CastleWindsor.pdb" "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib\net45"
copy "%CD%\..\URSA.Http.CastleWindsor\bin\Debug\URSA.CastleWindsor.xml" "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\lib\net45"
md "%CD%\..\NugetBuild\URSA.Owin\lib"
md "%CD%\..\NugetBuild\URSA.Owin\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Owin\lib\net45"
copy "%CD%\..\URSA.Owin\bin\Debug\netstandard1.6\URSA.Owin.dll" "%CD%\..\NugetBuild\URSA.Owin\lib\netstandard1.6"
copy "%CD%\..\URSA.Owin\bin\Debug\netstandard1.6\URSA.Owin.pdb" "%CD%\..\NugetBuild\URSA.Owin\lib\netstandard1.6"
copy "%CD%\..\URSA.Owin\bin\Debug\URSA.Owin.dll" "%CD%\..\NugetBuild\URSA.Owin\lib\net45"
copy "%CD%\..\URSA.Owin\bin\Debug\URSA.Owin.pdb" "%CD%\..\NugetBuild\URSA.Owin\lib\net45"
copy "%CD%\..\URSA.Owin\bin\Debug\URSA.Owin.xml" "%CD%\..\NugetBuild\URSA.Owin\lib\net45"
md "%CD%\..\NugetBuild\URSA.Web\lib"
md "%CD%\..\NugetBuild\URSA.Web\lib\netstandard1.6"
md "%CD%\..\NugetBuild\URSA.Web\lib\net45"
copy "%CD%\..\URSA.Web\bin\Debug\URSA.Web.dll" "%CD%\..\NugetBuild\URSA.Web\lib\net45"
copy "%CD%\..\URSA.Web\bin\Debug\URSA.Web.pdb" "%CD%\..\NugetBuild\URSA.Web\lib\net45"
copy "%CD%\..\URSA.Web\bin\Debug\URSA.Web.xml" "%CD%\..\NugetBuild\URSA.Web\lib\net45"
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Tools\URSA.Tools.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Core\URSA.Core.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Http\URSA.Http.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Http.Description\URSA.Http.Description.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.AutoFac\URSA.AutoFac.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.CastleWindsor\URSA.CastleWindsor.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Http.AutoFac\URSA.Http.AutoFac.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Http.CastleWindsor\URSA.Http.CastleWindsor.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Owin\URSA.Owin.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%
"%CD%\..\.nuget\NuGet.exe" pack "%CD%\..\NugetBuild\URSA.Web\URSA.Web.nuspec" -outputdirectory ".." -properties version=%PACKAGE_VERSION%