///<reference path="/bower_components/jquery/dist/jquery.js" />
///<reference path="/bower_components/angular/angular.js" />
///<reference path="/bower_components/bootstrap-sass-official/assets/javascripts/bootstrap.js" />
///<reference path="/bower_components/angular-animate/angular-animate.js" />
///<reference path="/bower_components/angular-cookies/angular-cookies.js" />
///<reference path="/bower_components/angular-messages/angular-messages.js" />
///<reference path="/bower_components/angular-resource/angular-resource.js" />
///<reference path="/bower_components/angular-route/angular-route.js" />
///<reference path="/bower_components/angular-sanitize/angular-sanitize.js" />
///<reference path="/bower_components/angular-touch/angular-touch.js" />
///<reference path="/bower_components/angular-bootstrap/ui-bootstrap-tpls.js" />
///<reference path="/bower_components/es6-promise/promise.js" />
///<reference path="/bower_components/jsonld/js/jsonld.js" />
///<reference path="/bower_components/uri-templates/uri-templates.js" />

/// <reference path="/app/scripts/app.js" />
/// <reference path="/app/scripts/ursa/prototype.js" />
/// <reference path="/app/scripts/ursa/model.js" />
/// <reference path="/app/scripts/ursa/view.js" />
/// <reference path="/app/scripts/ursa/filter.js" />
/// <reference path="/app/scripts/services/jsonld.js" />
/// <reference path="/app/scripts/services/configuration.js" />
/// <reference path="/app/scripts/services/ursa.js" />
/// <reference path="/app/scripts/filters/as-id.js" />
/// <reference path="/app/scripts/filters/stringify.js" />
/// <reference path="/app/scripts/directives/ursa.js" />
/// <reference path="/app/scripts/controllers/main.js" />
/// <reference path="/app/scripts/controllers/about.js" />

/// <reference path="/test/fixtures/api-documentation.js" />
/// <reference path="/test/matchers/toBeOfType.js" />
