//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using URSA.Web.Http;

namespace Test
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class TypeClient : Client
    {
        public TypeClient(Uri baseUri, string authenticationScheme) : base(baseUri, authenticationScheme)
        {
        }

        public TypeClient(Uri baseUri) : base(baseUri)
        {
        }

        public void List()
        {
            System.Collections.Generic.IDictionary<string, object> uriArguments = new System.Collections.Generic.Dictionary<string, object>();
            var accept = new string[0];
            var contentType = new string[0];
            Call(Verb.GET, "/type/#GET", accept, contentType, uriArguments);
        }

        public void Get(System.Int32 id)
        {
            System.Collections.Generic.IDictionary<string, object> uriArguments = new System.Collections.Generic.Dictionary<string, object>();
            var accept = new string[0];
            var contentType = new string[0];
            uriArguments["id"] = id;
            Call(Verb.GET, "/type/id/{?id}", accept, contentType, uriArguments);
        }
    }
}