//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    [RDeF.Mapping.Attributes.Class(Iri = "http://temp.uri/vocab#Article")]
    public interface IArticle : RDeF.Entities.IEntity
    {
        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#title")]
        System.Object title { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#body")]
        System.Object body { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#key")]
        System.Object key { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class Article : IArticle
    {
        private RDeF.Entities.Iri _iri = new RDeF.Entities.Iri("urn:guid:" + System.Guid.NewGuid());

        RDeF.Entities.IEntityContext RDeF.Entities.IEntity.Context { get { return null; } }

        RDeF.Entities.Iri RDeF.Entities.IEntity.Iri { get { return _iri; } }

        public System.Object title { get; set; }

        public System.Object body { get; set; }

        public System.Object key { get; set; }
    }
}