//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    [RomanticWeb.Mapping.Attributes.Class("http://temp.uri/vocab#Product")]
    public interface IIProduct : RomanticWeb.Entities.IEntity
    {
        [RomanticWeb.Mapping.Attributes.Property("http://temp.uri/vocab#name")]
        System.String Name { get; set; }

        [RomanticWeb.Mapping.Attributes.Property("http://temp.uri/vocab#price")]
        System.Double Price { get; set; }

        [RomanticWeb.Mapping.Attributes.Collection("http://temp.uri/vocab#feature")]
        System.Collections.Generic.IEnumerable<System.String> Features { get; set; }

        [RomanticWeb.Mapping.Attributes.Property("http://temp.uri/vocab#key")]
        System.Guid Key { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class IProduct : IIProduct
    {
        private RomanticWeb.Entities.EntityId _id = new RomanticWeb.Entities.EntityId(new System.Uri("urn:guid:" + System.Guid.NewGuid()));

        RomanticWeb.IEntityContext RomanticWeb.Entities.IEntity.Context { get { return null; } }

        RomanticWeb.Entities.EntityId RomanticWeb.Entities.IEntity.Id { get { return _id; } }

        public System.String Name { get; set; }

        public System.Double Price { get; set; }

        public System.Collections.Generic.IEnumerable<System.String> Features { get; set; }

        public System.Guid Key { get; set; }
    }
}