//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class IProductClient : Client
    {
        public IProductClient(Uri baseUri) : base(baseUri)
        {
        }

        public void Delete()
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[0];
            var contentType = new string[0];
            Call(Verb.DELETE, "/product/#DELETEId", accept, contentType, uriArguments);
        }

        public System.Collections.Generic.IEnumerable<Vocab.IIProduct> Get(RomanticWeb.Entities.EntityId id)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "application/rdf+xml",
                "application/owl+xml",
                "text/turtle",
                "application/ld+json" };
            var contentType = new string[] {
                "application/rdf+xml",
                "text/turtle",
                "application/owl+xml",
                "application/ld+json" };
            return Call<System.Collections.Generic.IEnumerable<Vocab.IIProduct>>(Verb.GET, "/product/#GETId", accept, contentType, uriArguments, id);
        }

        public RomanticWeb.Entities.EntityId Create(Vocab.IIProduct instance)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "application/rdf+xml",
                "text/turtle",
                "application/owl+xml",
                "application/ld+json" };
            var contentType = new string[] {
                "application/rdf+xml",
                "application/owl+xml",
                "text/turtle",
                "application/ld+json" };
            return Call<RomanticWeb.Entities.EntityId>(Verb.POST, "/product/#POSTProduct", accept, contentType, uriArguments, instance);
        }

        public void Update(Vocab.IIProduct instance)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[0];
            var contentType = new string[] {
                "application/rdf+xml",
                "application/owl+xml",
                "text/turtle",
                "application/ld+json" };
            Call(Verb.PUT, "/product/#PUTIdAndProduct", accept, contentType, uriArguments, instance);
        }

        public System.Collections.Generic.IEnumerable<Vocab.IIProduct> List(System.Int32 skip, System.Int32 take)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "application/rdf+xml",
                "text/turtle",
                "application/owl+xml",
                "application/ld+json" };
            var contentType = new string[0];
            uriArguments.skip = skip;
            uriArguments.take = take;
            return Call<System.Collections.Generic.IEnumerable<Vocab.IIProduct>>(Verb.GET, "/product?skip={?skip}&take={?take}", accept, contentType, uriArguments);
        }
    }
}