//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace URSA.Example.WebApplication.Data
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public interface IPerson : RomanticWeb.Entities.IEntity
    {
        System.String Firstname { get; set; }

        new System.Guid Id { get; set; }

        System.String Lastname { get; set; }

        System.Collections.Generic.IEnumerable<System.String> Roles { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class Person : IPerson
    {
        private RomanticWeb.Entities.EntityId _id = new RomanticWeb.Entities.EntityId(new System.Uri("urn:guid:" + System.Guid.NewGuid()));

        RomanticWeb.IEntityContext RomanticWeb.Entities.IEntity.Context { get { return null; } }

        RomanticWeb.Entities.EntityId RomanticWeb.Entities.IEntity.Id { get { return _id; } }

        public System.String Firstname { get; set; }

        public System.Guid Id { get; set; }

        public System.String Lastname { get; set; }

        public System.Collections.Generic.IEnumerable<System.String> Roles { get; set; }
    }
}