//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace URSA.Example.WebApplication.Data
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class PersonClient : Client
    {
        public PersonClient(Uri baseUri) : base(baseUri)
        {
        }

        public System.Guid Create(URSA.Example.WebApplication.Data.IPerson instance)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "text/xml",
                "application/xml",
                "application/json" };
            var contentType = new string[] {
                "application/xml",
                "text/xml",
                "application/json" };
            return Call<System.Guid>(Verb.POST, "/person/#POSTPerson", accept, contentType, uriArguments, instance);
        }

        public System.Collections.Generic.IEnumerable<URSA.Example.WebApplication.Data.IPerson> List(System.Int32 skip, System.Int32 take)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "application/xml",
                "application/json",
                "text/xml" };
            var contentType = new string[0];
            uriArguments.skip = skip;
            uriArguments.take = take;
            return Call<System.Collections.Generic.IEnumerable<URSA.Example.WebApplication.Data.IPerson>>(Verb.GET, "/person?skip={?skip}&take={?take}", accept, contentType, uriArguments);
        }

        public void Delete(System.Guid id)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[0];
            var contentType = new string[0];
            uriArguments.id = id;
            Call(Verb.DELETE, "/person/id/{?id}", accept, contentType, uriArguments);
        }

        public void Update(System.Guid id, URSA.Example.WebApplication.Data.IPerson instance)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[0];
            var contentType = new string[] {
                "application/xml",
                "application/json",
                "text/xml" };
            uriArguments.id = id;
            Call(Verb.PUT, "/person/id/{?id}", accept, contentType, uriArguments, instance);
        }

        public URSA.Example.WebApplication.Data.IPerson Get(System.Guid id)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[] {
                "application/xml",
                "application/json",
                "text/xml" };
            var contentType = new string[0];
            uriArguments.id = id;
            return Call<URSA.Example.WebApplication.Data.IPerson>(Verb.GET, "/person/id/{?id}", accept, contentType, uriArguments);
        }

        public void SetRoles(System.Guid id, System.Collections.Generic.IEnumerable<System.String> roles)
        {
            dynamic uriArguments = new ExpandoObject();
            var accept = new string[0];
            var contentType = new string[] {
                "application/xml",
                "application/json",
                "text/xml" };
            uriArguments.id = id;
            Call(Verb.PUT, "/person/roles/id/{?id}", accept, contentType, uriArguments, roles);
        }
    }
}