//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    [RDeF.Mapping.Attributes.Class(Iri = "http://temp.uri/vocab#Product")]
    public interface IProduct : RDeF.Entities.IEntity
    {
        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#name")]
        System.Object name { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#price")]
        System.Object price { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#feature")]
        System.Object feature { get; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#category")]
        System.Object category { get; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#partOf")]
        System.Object partOf { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#similar")]
        System.Object similar { get; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#replacement")]
        System.Object replacement { get; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#key")]
        System.Object key { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class Product : IProduct
    {
        private RDeF.Entities.Iri _iri = new RDeF.Entities.Iri("urn:guid:" + System.Guid.NewGuid());

        RDeF.Entities.IEntityContext RDeF.Entities.IEntity.Context { get { return null; } }

        RDeF.Entities.Iri RDeF.Entities.IEntity.Iri { get { return _iri; } }

        public System.Object name { get; set; }

        public System.Object price { get; set; }

        public System.Object feature { get; }

        public System.Object category { get; }

        public System.Object partOf { get; set; }

        public System.Object similar { get; }

        public System.Object replacement { get; }

        public System.Object key { get; set; }
    }
}