//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Dynamic;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    [RDeF.Mapping.Attributes.Class(Iri = "http://temp.uri/vocab#Product")]
    public interface IProduct : RDeF.Entities.IEntity
    {
        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#name")]
        System.String Name { get; set; }

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#price")]
        System.Double Price { get; set; }

        [RDeF.Mapping.Attributes.Collection(Iri = "http://temp.uri/vocab#feature")]
        System.Collections.Generic.ICollection<System.String> Features { get;}

        [RDeF.Mapping.Attributes.Collection(Iri = "http://temp.uri/vocab#category")]
        System.Collections.Generic.IList<System.String> Categories { get;}

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#partOf")]
        Vocab.IProduct PartOf { get; set; }

        [RDeF.Mapping.Attributes.Collection(Iri = "http://temp.uri/vocab#similar")]
        System.Collections.Generic.ICollection<Vocab.IProduct> Similar { get;}

        [RDeF.Mapping.Attributes.Collection(Iri = "http://temp.uri/vocab#replacement")]
        System.Collections.Generic.IList<Vocab.IProduct> Replacements { get;}

        [RDeF.Mapping.Attributes.Property(Iri = "http://temp.uri/vocab#key")]
        System.Guid Key { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class Product : IProduct
    {
        private RDeF.Entities.Iri _iri = new RDeF.Entities.Iri("urn:guid:" + System.Guid.NewGuid());

        RDeF.Entities.IEntityContext RDeF.Entities.IEntity.Context { get { return null; } }

        RDeF.Entities.Iri RDeF.Entities.IEntity.Iri { get { return _iri; } }

        public System.String Name { get; set; }

        public System.Double Price { get; set; }

        private System.Collections.Generic.ICollection<System.String> _features = new System.Collections.Generic.List<System.String>();

        public System.Collections.Generic.ICollection<System.String> Features { get { return _features; } }

        private System.Collections.Generic.IList<System.String> _categories = new System.Collections.Generic.List<System.String>();

        public System.Collections.Generic.IList<System.String> Categories { get { return _categories; } }

        public Vocab.IProduct PartOf { get; set; }

        private System.Collections.Generic.ICollection<Vocab.IProduct> _similar = new System.Collections.Generic.List<Vocab.IProduct>();

        public System.Collections.Generic.ICollection<Vocab.IProduct> Similar { get { return _similar; } }

        private System.Collections.Generic.IList<Vocab.IProduct> _replacements = new System.Collections.Generic.List<Vocab.IProduct>();

        public System.Collections.Generic.IList<Vocab.IProduct> Replacements { get { return _replacements; } }

        public System.Guid Key { get; set; }
    }
}