//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a URSA HTTP client proxy generation tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using URSA.Web.Http;

namespace Vocab
{
    [System.CodeDom.Compiler.GeneratedCode("URSA HTTP client proxy generation tool", "1.0")]
    public partial class ProductClient : Client
    {
        public ProductClient(HttpUrl baseUri, string authenticationScheme) : base(baseUri, authenticationScheme)
        {
        }

        public ProductClient(HttpUrl baseUri) : base(baseUri)
        {
        }
    }
}